[package]
name = "murabito_kinds"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bevy.workspace = true
murabito_actions.workspace = true
murabito_hexcoords.workspace = true
murabito_movement.workspace = true

[dev-dependencies]
murabito_progress.workspace = true
