[package]
name = "murabito_brainstem"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bevy.workspace = true
murabito_actions.workspace = true
murabito_hexcoords.workspace = true
murabito_identity.workspace = true
murabito_perception.workspace = true
murabito_placement.workspace = true
murabito_progress.workspace = true
murabito_vision.workspace = true

[dev-dependencies]
murabito_movement.workspace = true
