[package]
name = "murabito"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bevy.workspace = true
murabito_scene.workspace = true
murabito_camera.workspace = true
murabito_movement.workspace = true
murabito_progress.workspace = true
murabito_actions.workspace = true
murabito_user_data.workspace = true
murabito_settings.workspace = true
murabito_i18n.workspace = true
murabito_app_state.workspace = true
